export const HOME_ROUTE = '/'
export const GENRE_ROUTE = 'genre'
export const FILMS_ROUTE = '/films'
export const FILM_ITEM_ROUTE = '/film'
export const AUTH_ROUTE = '/Auth'
export const LOGIN_ROUTE = '/login'
export const REGISTER_ROUTE = '/registration'
export const PROFILE_ROUTE = '/profile'

// export const HOME_ROUTE = '/movies'
